# Generated by Django 4.2.5 on 2024-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_item_amount_alter_item_name_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
    ]
