# Generated by Django 4.2.5 on 2024-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('Air', 'Air'), ('Sea', 'Sea')], default='Air', max_length=255, null=True, verbose_name='Type'),
        ),
    ]
