# Generated by Django 4.2.5 on 2024-08-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='emailfield_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='EmailField 1'),
        ),
        migrations.AddField(
            model_name='item',
            name='filefield_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='FileField 1'),
        ),
    ]
