# Generated by Django 4.2.5 on 2024-08-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_item_emailfield_1_item_filefield_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='emailfield_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='filefield_1',
        ),
    ]
