# Generated by Django 4.2.5 on 2024-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_item_emailfield_1_remove_item_filefield_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decimalfield_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DecimalField 1'),
        ),
    ]
