# Generated by Django 4.2.5 on 2024-08-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_item_decimalfield_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='decimalfield_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
