# Generated by Django 4.2.5 on 2024-08-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='first_name',
        ),
    ]
