# Generated by Django 4.2.5 on 2024-08-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_rename_name_item_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='first_name',
        ),
    ]
