# Generated by Django 4.2.5 on 2024-08-02 15:41

import core.models.template
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='David',
            fields=[
                ('id', models.CharField(default=core.models.template.generate_random_slug, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('charfield_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='CharField 1')),
                ('numberfield_1', models.IntegerField(blank=True, null=True, verbose_name='NumberField 1')),
                ('decimalfield_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DecimalField 1')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(default=core.models.template.generate_random_slug, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('numberfield_1', models.IntegerField(blank=True, null=True, verbose_name='NumberField 1')),
                ('decimalfield_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DecimalField 1')),
                ('booleanfield_1', models.BooleanField(blank=True, null=True, verbose_name='BooleanField 1')),
                ('datefield_1', models.DateField(blank=True, null=True, verbose_name='DateField 1')),
                ('decimalfield_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DecimalField 2')),
                ('datetimefield_1', models.DateTimeField(blank=True, null=True, verbose_name='DateTimeField 1')),
                ('slugfield_1', models.SlugField(blank=True, null=True, verbose_name='SlugField 1')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
