# Generated by Django 4.2.5 on 2024-08-03 14:21

import core.models.template
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arifahub', '0002_david_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nextt',
            fields=[
                ('id', models.CharField(default=core.models.template.generate_random_slug, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
