# Generated by Django 4.2.5 on 2024-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arifahub', '0003_nextt'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextt',
            name='datefield_1',
            field=models.DateField(blank=True, null=True, verbose_name='DateField 1'),
        ),
    ]
