# Generated by Django 4.2.5 on 2024-08-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arifahub', '0004_nextt_datefield_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='david',
            name='first_name',
        ),
    ]
