# Generated by Django 4.2.5 on 2024-08-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='charfield_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CharField 1'),
        ),
        migrations.AddField(
            model_name='try',
            name='textfield_1',
            field=models.TextField(blank=True, null=True, verbose_name='TextField 1'),
        ),
    ]
