# Generated by Django 4.2.5 on 2024-08-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='floatfield_1',
            field=models.FloatField(blank=True, null=True, verbose_name='FloatField 1'),
        ),
        migrations.AddField(
            model_name='turn',
            name='foreignkey_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.try', verbose_name='ForeignKey 1'),
        ),
    ]
