# Generated by Django 4.2.5 on 2024-08-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='david',
            name='datefield_1',
            field=models.DateField(blank=True, null=True, verbose_name='DateField 1'),
        ),
        migrations.AddField(
            model_name='david',
            name='decimalfield_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DecimalField 1'),
        ),
        migrations.AddField(
            model_name='david',
            name='floatfield_1',
            field=models.FloatField(blank=True, null=True, verbose_name='FloatField 1'),
        ),
    ]
