# Generated by Django 4.2.5 on 2024-08-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_david_datefield_1_david_decimalfield_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='david',
            name='datefield_1',
        ),
        migrations.AddField(
            model_name='david',
            name='daten',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='DateField 1'),
        ),
        migrations.AlterField(
            model_name='david',
            name='floatfield_1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='FloatField 1'),
        ),
    ]
