# Generated by Django 4.2.5 on 2024-07-16 16:27

import core.models.template
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default=core.models.template.generate_random_slug, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
