# Generated by Django 4.2.5 on 2024-08-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_changelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='user',
        ),
    ]
