# Generated by Django 4.2.5 on 2024-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_changelog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
