# Generated by Django 4.2.5 on 2024-07-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_app_status_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app', to='core.app'),
            preserve_default=False,
        ),
    ]
