# Generated by Django 4.2.5 on 2024-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
