# Generated by Django 4.2.5 on 2024-07-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_app_edit_history_document_edit_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='edit_history',
        ),
        migrations.RemoveField(
            model_name='document',
            name='edit_history',
        ),
        migrations.RemoveField(
            model_name='module',
            name='edit_history',
        ),
    ]
