# Generated by Django 4.2.5 on 2024-07-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_app_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('app_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.app')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.app')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.app',),
        ),
    ]
