# Generated by Django 4.2.5 on 2024-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danci',
            name='charfield_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CharField 1'),
        ),
        migrations.AddField(
            model_name='danci',
            name='datefield_1',
            field=models.DateField(blank=True, null=True, verbose_name='DateField 1'),
        ),
        migrations.AddField(
            model_name='danci',
            name='decimalfield_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DecimalField 1'),
        ),
    ]
