# Generated by Django 4.2.5 on 2024-08-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0002_danci_charfield_1_danci_datefield_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danci',
            old_name='datefield_1',
            new_name='datefield',
        ),
    ]
