# Generated by Django 4.2.5 on 2024-08-04 23:24

import core.models.template
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0012_alter_danci_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danci',
            name='id',
            field=models.CharField(default=core.models.template.generate_random_slug, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
