# Generated by Django 4.2.5 on 2024-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0024_alter_danci_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='000000', max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
