# Generated by Django 4.2.5 on 2024-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0025_cold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cold',
            name='decimalfield_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DecimalField 1'),
        ),
        migrations.AddField(
            model_name='cold',
            name='emailfield_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='EmailField 1'),
        ),
    ]
