# Generated by Django 4.2.5 on 2024-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0026_cold_decimalfield_1_cold_emailfield_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cold',
            name='emailfield_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='EmailField '),
        ),
    ]
