# Generated by Django 4.2.5 on 2024-08-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0028_say'),
    ]

    operations = [
        migrations.AddField(
            model_name='say',
            name='booleanfield_1',
            field=models.BooleanField(blank=True, null=True, verbose_name='BooleanField 1'),
        ),
        migrations.AddField(
            model_name='say',
            name='selectfield_1',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True, verbose_name='SelectField 1'),
        ),
    ]
