# Generated by Django 4.2.5 on 2024-08-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0030_say_foreignkey_1_say_manytomanyfield_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='say',
            name='foreignkey_1',
        ),
        migrations.RemoveField(
            model_name='say',
            name='manytomanyfield_1',
        ),
    ]
