# Generated by Django 4.2.5 on 2024-08-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0031_remove_say_foreignkey_1_remove_say_manytomanyfield_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='say',
            name='foreignkey_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masafa.cold', verbose_name='ForeignKey 1'),
        ),
    ]
