# Generated by Django 4.2.5 on 2024-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa', '0032_say_foreignkey_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='say',
            name='manytomanyfield_1',
            field=models.ManyToManyField(blank=True, null=True, to='masafa.danci', verbose_name='ManyToManyField 1'),
        ),
    ]
